---
title: "Complaints Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}

library(flexdashboard)
library(tidyverse)
library(lubridate)
library(janitor)
library(glue)
library(plotly)
library(DT)
library(kableExtra)
library(htmlwidgets)
library(htmltools)
library(readxl)
```

Column {data-width=650}
-----------------------------------------------------------------------

### States and Number of Complaints

```{r}



fig <- plot_ly(complaints)
  x = c(state)
  y = c(count(complaints))
  type = "bar"
  color = "red"
fig <- fig %>% layout(title = "States and Number of Complaints",
         xaxis = list(title = "States"),
         yaxis = list (title = "Number of Complaints"))
fig



### R told me to make a scatter plot instead
fig <- plot_ly(data = complaints, x = ~state, y = ~complaints)

fig 



```

Column {data-width=350}
-----------------------------------------------------------------------

### Companies and Number of Complaints

```{r}



fig <- plot_ly(complaints)
  x = c(company)
  y = c(count(complaints))
  type = "bar"
  color = "red"
fig <- fig %>% layout(title = "Companies and Number of Complaints",
         xaxis = list(title = "Companies"),
         yaxis = list (title = "Number of Complaints"))
fig



```

### Companies That Gave Monetary Relief

```{r}


fig <- plot_ly(complaints)
  x = c(company)
  y = c(count(complaints))
  type = "bar"
  color = "red"
fig <- fig %>% layout(title = "Companies That Gave Monetary Relief",
         xaxis = list(title = "Company"),
         yaxis = list (title = "Gave Monetary Relief"))
fig
```

